# Dockerfile был загружен в dockerhub под название alexdemure/bustail:frontend
# https://hub.docker.com/layers/134427848/alexdemure/bustail/frontend/images/sha256-c37a7a200dff79c9d886f2afd5b6338ed79b7e41a9867edda1cab5d20ec67aaf?context=explore

FROM node:15.6-alpine

WORKDIR /app

COPY package.json /app/package.json

RUN npm install

COPY . /app

EXPOSE 4000

CMD ["npm", "start"]
