version: "3.8"

volumes:
  versions:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    network_mode: bridge
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: ./env_files/postgres.env

  core:
    build: backend
    container_name: core
    hostname: core
    network_mode: bridge
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
    links:
      - postgres
    env_file:
      - ./env_files/postgres.env
      - ./env_files/global.env
    volumes:
      - ./backend/alembic/versions:/app/backend/alembic/versions
      - ./backend/test.db:/app/backend/test.db

