version: "3.8"

volumes:
  redis_data:
  pgdata:


services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: ./env_files/postgres.env

  core:
    image: alexdemure/bustail:core
    container_name: core
    hostname: core
    network_mode: "host"
    ports:
      - "7040:7040"
    depends_on:
      - "postgres"
      - "redis"
    env_file:
      - ./env_files/postgres.env
      - ./env_files/global.env
      - ./env_files/mailing.env
      - ./env_files/redis.env
    volumes:
      - ./backend:/app/backend/

  frontend:
    image: alexdemure/bustail:frontend_prod
    container_name: frontend
    hostname: frontend
    network_mode: host
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app/

  redis:
    image: "redis:alpine"
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command:
      - 'redis-server'
      - '--requirepass foobared'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
    volumes:
      - redis_data:/data
