version: "3.8"


services:
  core:
    build: core/
    container_name: core
    hostname: core
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    network_mode: bridge
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: core/env_files/postgres.env
