version: 2.1

commands:
  build_app:
    steps:
      - add_ssh_keys
      - run:
          name: Add to known hosts
          command: |
            mkdir -p ~/.ssh/
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: git pull
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail_core && git pull"
      - run:
          name: install requirements for test
          command: |
              ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail_core/backend && export YANDEX_ACCESS_KEY_ID=UefYhTqRQsB_oNVErPLA && export YANDEX_SECRET_ACCESS_KEY=74jLKEMaKfUUgeZhSoqj1QSygCCGAJzYKMNh6hY2 && export YANDEX_BUCKET_NAME=bustail && export POSTGRES_DB=bustail && export POSTGRES_USER=postgres && export POSTGRES_PASSWORD=bustail && export POSTGRES_SERVER=127.0.0.1 && export MAILING_SECRET_KEY=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 && export MAILING_EMAIL=alexanderdemure@gmail.com && export MAILING_NAME=Bustail && export REDIS_HOST=localhost && export REDIS_DB=0 && export REDIS_PORT=6379 && export REDIS_PASSWORD=foobared && python3 -m pytest --junitxml=test-results/junit.xml"

      - store_test_results:
          path: /home/alex/bustail_core/backend/test-results/

      - store_artifacts:
          path: /home/alex/bustail_core/backend/test-results/


#      - run:
#          name: Docker-compose up
#          command: |
#            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail_core && docker-compose -f $CFG_NAME up -d --build"
#      - run:
#          name: Docker-compose logs
#          command: |
#            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail_core && docker-compose -f $CFG_NAME logs --tail="10""

jobs:
  build:
    docker:
      - image: 'cimg/base:2021.01'
    steps:
      - build_app


workflows:
  version: 2.1
  build-and-deploy-prod:
    jobs:
      - build:
          context:
            - Production
          filters:
            branches:
              only:
                - master
