version: 2.1

commands:
  build_app:
    steps:
      - add_ssh_keys
      - run:
          name: Add to known hosts
          command: |
            mkdir -p ~/.ssh/
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: git pull
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail_core && git pull"
      - run:
          name: Docker-compose up
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail_core && docker-compose -f $CFG_NAME up -d --build"
      - run:
          name: Docker-compose logs
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/alex/bustail_core && docker-compose -f $CFG_NAME logs"

jobs:
  build:
    docker:
      - image: 'cimg/base:2021.01'
    steps:
      - build_app


workflows:
  version: 2.1
  build-and-deploy-prod:
    jobs:
      - build:
          context:
            - Production
          filters:
            branches:
              only:
                - master
