"""hello

Revision ID: 42d87da4fa86
Revises: e83287861c0f
Create Date: 2020-07-05 13:56:50.467196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d87da4fa86'
down_revision = 'e83287861c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorization_data', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_authorization_data_account_id'), 'authorization_data', ['account_id'], unique=False)
    op.create_foreign_key(None, 'authorization_data', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authorization_data', type_='foreignkey')
    op.drop_index(op.f('ix_authorization_data_account_id'), table_name='authorization_data')
    op.drop_column('authorization_data', 'account_id')
    # ### end Alembic commands ###
