"""hello

Revision ID: 97f39228ebb1
Revises: 5599e49e9b01
Create Date: 2020-07-05 13:39:51.107725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f39228ebb1'
down_revision = '5599e49e9b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
